### PR TITLE
Fix upload e2e test timeout.

### PR DESCRIPTION
**Pull request by Askir**

### CODE REVIEW

**Comment by Askir** [comment]
Ran the pipeline twice now and it didn't crash. Going to start a third time but I think this fixed it.

**Comment by erksch** [comment]
If it works, great! But I think the main problem is that we are waiting for the request @uploadImage twice.
See [this line: `cy.wait(['@uploadImage', '@uploadImage'])`](https://github.com/hpi-sam/ask-your-repository-web/pull/56/files#diff-86539732b2c59a48174d8f246af21b2cR64). It waits for the same type of request twice. Sometimes this works sometimes not maybe if the requests are to simultaniously to be picked up properly. There are some open issues about this https://github.com/cypress-io/cypress/issues/2227. Someone even did a stress test to replicate that.

**Comment by erksch** [comment]
Waiting might fix the problem in that way that it makes the two requests more distinguishable.

**Comment by erksch** [comment]
Closed in favor of #57

**Pull request closed without merging**
